apiVersion: v1
kind: Secret
metadata:
  name: mariadb-creds
data:
  password: cm9vdA==
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  database: db_banka1
  username: root
  passwordSecretKeyRef:
    name: mariadb-creds
    key: password
  rootPasswordSecretKeyRef:
    name: mariadb-creds
    key: password
  volumeClaimTemplate:
    resources:
      requests:
        storage: 2Gi
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce

  connection:
    secretName: mariadb-conn
    secretTemplate:
      key: dsn

  image:
    repository: mariadb
    tag: "10.11.3"
    pullPolicy: IfNotPresent

  port: 3306

  replicas: 3

  replication:
    primary:
      podIndex: 0
      automaticFailover: true
      service:
        type: ClusterIP
      connection:
        secretName: primary-mariadb-conn
        secretTemplate:
          key: dsn
    replica:
      waitPoint: AfterCommit
      gtid: CurrentPos
      connectionTimeout: 10s
      connectionRetries: 10
      syncTimeout: 10s
    syncBinlog: true

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  service:
    type: ClusterIP
