apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bank-service
  name: bank-service
  namespace: __NAMESPACE__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/banka-1/bank-service:__COMMIT_HASH__
          imagePullPolicy: Always
          name: bank-service
          env:
            - name: spring.datasource.hikari.jdbcUrl
              value: jdbc:mysql://primary-mariadb:3306/db_banka1?createDatabaseIfNotExist=true
            - name: spring.jpa.hibernate.ddl-auto
              value: update
            - name: password.reset.endpoint
              value: https://__DOMAIN__/reset-password
            - name: password.activate.endpoint
              value: https://__DOMAIN__/activate-password
          ports:
            - containerPort: 8074
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bank-service
  name: bank-service
  namespace: __NAMESPACE__
spec:
  ports:
    - port: 8074
      protocol: TCP
      targetPort: 8074
  selector:
    app: bank-service
  type: ClusterIP
